spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://msa-exam-rds.cp4cwm684hgx.ap-northeast-2.rds.amazonaws.com/msa_exam?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password